<?xml version="1.0" encoding="utf-8"?><Database Name="FeedbackScript" Class="trackingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=FPDBMS14V;Initial Catalog=FeedbackScript;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FeedbackScriptConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Comments" Member="Comments">
    <Type Name="Comment">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="Agency" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UtcDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Positive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Comment" Member="Comment1" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Responses" Member="Responses">
    <Type Name="Response">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="Agency" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UtcDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Positive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>